#!/bin/sh
riscof --verbose info run --config ./config64.ini --suite ./riscv-arch-test/riscv-test-suite/rv64i_m --env ./riscv-arch-test/riscv-test-suite/env
riscof --verbose info run --config ./config32.ini --suite ./riscv-arch-test/riscv-test-suite/rv32i_m --env ./riscv-arch-test/riscv-test-suite/env
